# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Irregular Motif
email: eric--dotgoeshere--engstrom@something-exactly-like-gmail-dot-com
description: >- # this means to ignore newlines until "baseurl:"
  Whatever, Wherefore, and Why(not), but only occasionally and intermittently.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: crimson_egret
github_username:  eengstrom

# Build settings
markdown: kramdown
theme: minima
# https://github.com/jekyll/minima

plugins:
  - jekyll-feed

# Set up permalinks
#/blog/:year/:month/:day/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - convert
  - serve.sh
  - 00-README.md
  - _posts/2018-12-12-welcome-to-jekyll.markdown
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
